// default package
// Generated Oct 7, 2018 2:16:31 PM by Hibernate Tools 5.3.0.Beta2
package Models;
/**
 * Languages generated by hbm2java
 */
public class Languages implements java.io.Serializable {

	private Integer id;
	private Developers developers;
	private String code;

	public Languages() {
	}

	public Languages(Developers developers, String code) {
		this.developers = developers;
		this.code = code;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Developers getDevelopers() {
		return this.developers;
	}

	public void setDevelopers(Developers developers) {
		this.developers = developers;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
