// default package
// Generated Oct 7, 2018 2:16:31 PM by Hibernate Tools 5.3.0.Beta2
package Models;
/**
 * Programminglanguages generated by hbm2java
 */
public class TempUpdateProgramminglanguages implements java.io.Serializable {

	private Integer id;
	private String inname;
	private String outname;
	private String developers;

	public TempUpdateProgramminglanguages() {
	}

	
	
	public TempUpdateProgramminglanguages(String inname, String outname, String developers) {
		this.inname = inname;
		this.outname = outname;
		this.developers = developers;
	}



	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDevelopers() {
		return developers;
	}

	public void setDevelopers(String developers) {
		this.developers = developers;
	}

	public String getInname() {
		return inname;
	}

	public void setInname(String inname) {
		this.inname = inname;
	}

	public String getOutname() {
		return outname;
	}

	public void setOutname(String outname) {
		this.outname = outname;
	}

	

}
